name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go-discovery-kit-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/discovery_kit_api
    steps:
    - uses: actions/checkout@v4
      with:
        # increased fetch depth to support git diff
        fetch-depth: 2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - run: ./build.sh
    - run: git diff --exit-code
      name: "Ensure that Go API changes (as a consequence of OpenAPI spec changes) are checked in"
    - run: go get
    - run: go test

  go-discovery-kit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/discovery_kit_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Audit
        run: |
          go mod download
          make audit