name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go-discovery-kit-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/discovery_kit_api
    steps:
    - uses: actions/checkout@v3
      with:
        # increased fetch depth to support git diff
        fetch-depth: 2
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.0'
    - run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@2cf7fcf5b26d1a4362e7c300bd65c20f4f6c4298
    - run: ./build.sh
    - run: git diff --exit-code
      name: "Ensure that Go API changes (as a consequence of OpenAPI spec changes) are checked in"
    - run: go get
    - run: go test